### ISSUE TITLE
Gutenberg doesn't quite work on the front end

### ISSUE THREAD

**Issue by robertk1997** [FlusherDock1/Gutenberg#35]
I'm quite new to OctoberCMS and everything involved with it. It's been a slow learning process for me. Basically, I'm trying to make a blog website and I decided to use gutenberg seeing that I used to use wordpress and have always liked the layout. 
So, I installed it, went to settings, enabled it - and it works on the backend just fine with the Rainlab blog plugin. The problem is, when I publish the post, it looks nothing like it does in the back end.
I added the laraberg.css file into my blog post cms page and the formatting became better but it's still not rendering the line spacing, the general spacing, colors, h1,h2,h3, basically anything that makes a post look nice. 
I'm using the {{post.content_html|raw}} for rendering the content and I mean it shows up and everything but it doesn't save the same format as it had in the backend. Am I doing something wrong? I've assumed that since it's already integrated with Rainlab blogs I shouldn't have to do the public implement stuff?

And if I do need to, could you explain it in a more specific way, I don't understand in the documentation what you mean when you say "add it to your model". Since I'm new I'm thinking "what model where?". 

Thank you for your time, my website is nationaldossier.com if you want to see the posts and how the look just click on one of the front page posts.

**Comment by chiragsenjaliya** [comment]
@robertk1997  try to add this css instead 
<link href="/plugins/reazzon/gutenberg/formwidgets/gutenberg/assets/css/laraberg.css" rel="stylesheet">

**Comment by robertk1997** [comment]
> @robertk1997 try to add this css instead
> `<link href="/plugins/reazzon/gutenberg/formwidgets/gutenberg/assets/css/laraberg.css" rel="stylesheet">`

A few things got better but also a few things got worse.... https://nationaldossier.com/blog/post/test-post-gutenberg 

It used to be that the text on the cover element would render behind the opacity filter, now it's in front but its still loading up as full sized. And now text runs straight off the side of the page when I have too much spacing it seems.

**Comment by robertk1997** [comment]
For some reason my own sites CSS is interfering with the cover photo I guess. I wonder what could cause that without going through every line of CSS?

**Comment by robertk1997** [comment]
Thank you very much though I appreciate it! Its all pretty much working now.

**Comment by FlusherDock1** [comment]
Hi. I'm sorry but i really can't do anything about this problem. Gutenberg JS core is really hard coded for only WP use. More of 99% of troubles that coming from Gutenberg in OctoberCMS enviroment is coming from it's JS core. So there is nothing any of us can do about it.

Right now, i'm more concentrated in Editor.Js formwidget plugin, it is really good alternative for gutenberg in OctoberCMS enviroment. It's powerfull, lightweight, easy extendible, you can create your own blocks, and even publish it in marketplace for your own price. try concidering using it instead of Gutenberg and help community to grow up a blocks libriary, by creating and publishng your own.
