### ISSUE TITLE
How to add Transform to in editor?

### ISSUE THREAD

**Issue by chiragsenjaliya** [FlusherDock1/Gutenberg#36]
Hey,
I am using this plugin and it works great! But there is something I am curious about!

When I click on paragraph it doesn't show me block for transform to can you tell me how can I enable it?

![image](https://user-images.githubusercontent.com/19857731/89313309-f65d4400-d695-11ea-8897-ffbdd8f3f494.png)

this is on Gutenberg editor

![image](https://user-images.githubusercontent.com/19857731/89312970-8a7adb80-d695-11ea-9bbf-8e5aa9ba3a7d.png)

**Comment by FlusherDock1** [comment]
Hi. I'm sorry but i really can't do anything about this problem. Gutenberg JS core is really hard coded for only WP use. More of 99% of troubles that coming from Gutenberg in OctoberCMS enviroment is coming from it's JS core. So there is nothing any of us can do about it.

Right now, i'm more concentrated in Editor.Js formwidget plugin, it is really good alternative for gutenberg in OctoberCMS enviroment. It's powerfull, lightweight, easy extendible, you can create your own blocks, and even publish it in marketplace for your own price. try concidering using it instead of Gutenberg and help community to grow up a blocks libriary, by creating and publishng your own.

**Comment by chiragsenjaliya** [comment]
@FlusherDock1 issue was with compiled js. I have set up Gutenberg and compiled it and it is working. I am using Gutenberg release 8.1
