### ISSUE TITLE
API handler not found

### ISSUE THREAD

**Issue by Donokami** [FlusherDock1/Gutenberg#37]
Hey,
And thanks for your work.
I have an issue in Gutenberg, using it with Rainlab.blog integration:
I've got this error that shows sometimes in the editor:
`API handler not found. - /wp/v2/media/5449?context=edit&_locale=user`

Also, it doesn't always save the editions made to the post, and when going on another post, Gutenberg ask us if we want to restore the other post.
That's quite annoying, if you have any solutions it would be amazing!

**Comment by FlusherDock1** [comment]
Hi. I'm sorry but i really can't do anything about this problem. Gutenberg JS core is really hard coded for only WP use. More of 99% of troubles that coming from Gutenberg in OctoberCMS enviroment is coming from it's JS core. So there is nothing any of us can do about it.

Right now, i'm more concentrated in Editor.Js formwidget plugin, it is really good alternative for gutenberg in OctoberCMS enviroment. It's powerfull, lightweight, easy extendible, you can create your own blocks, and even publish it in marketplace for your own price. try concidering using it instead of Gutenberg and help community to grow up a blocks libriary, by creating and publishng your own.
