### ISSUE TITLE
Embeds not working

### ISSUE THREAD

**Issue by Donokami** [FlusherDock1/Gutenberg#38]
When I try to embed a Youtube link or a tweet, it appers in the article front as a link in raw text.
Here is an example:
 https://www.youtube.com/watch?v=7ceNf9qJjgc 
Appears as:
```
<!-- wp:core-embed/youtube {"url":"https://www.youtube.com/watch?v=7ceNf9qJjgc","type":"video","providerNameSlug":"youtube","className":"wp-embed-aspect-16-9 wp-has-aspect-ratio wp-embed-aspect-4-3"} -->
<figure class="wp-block-embed-youtube wp-block-embed is-type-video is-provider-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio wp-embed-aspect-4-3"><div class="wp-block-embed__wrapper">
https://www.youtube.com/watch?v=7ceNf9qJjgc
</div></figure>
<!-- /wp:core-embed/youtube -->
```

**Comment by FlusherDock1** [comment]
Hi. I'm sorry but i really can't do anything about this problem. Gutenberg JS core is really hard coded for only WP use. More of 99% of troubles that coming from Gutenberg in OctoberCMS enviroment is coming from it's JS core. So there is nothing any of us can do about it.

Right now, i'm more concentrated in Editor.Js formwidget plugin, it is really good alternative for gutenberg in OctoberCMS enviroment. It's powerfull, lightweight, easy extendible, you can create your own blocks, and even publish it in marketplace for your own price. try concidering using it instead of Gutenberg and help community to grow up a blocks libriary, by creating and publishng your own.
